-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE public.login_attempts (
--   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--   user_id UUID NOT NULL,
--   success BOOLEAN NOT NULL,
--   timestamp TIMESTAMPTZ NOT NULL DEFAULT now(),
--   ip_address TEXT,
--   user_agent TEXT,
--
--   CONSTRAINT fk_user
--     FOREIGN KEY (user_id)
--     REFERENCES auth.users(id)
--     ON DELETE CASCADE
-- );
