version: '3.8'

services:
  sap_backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: power-of-europe-backend
    environment:
      - MISTRAL_API_KEY=${MISTRAL_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ENVIRONMENT=development
    ports:
      - "8013:8013"
    volumes:
      - ./backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8013 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
